### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './llms' is not defined by "exports"

### ISSUE THREAD

**Issue by zabil** [run-llama/LlamaIndexTS#1011]
Hi, sorry if this has already been fixed, but I couldn't find anything in the issues or discussions. I'm trying to run a basic example using the instructions from https://www.npmjs.com/package/llamaindex. However, I get an error when

running the `example.ts` file.

```
$ node --import tsx example.ts

node:internal/modules/esm/resolve:299
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './llms' is not defined by "exports" in /Users/--/node_modules/@llamaindex/core/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:299:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:646:9)
    at resolveExports (node:internal/modules/cjs/loader:628:36)
    at Module._findPath (node:internal/modules/cjs/loader:718:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1205:27)
    at m._resolveFilename (file:///Users/--/node_modules/tsx/dist/register-Cehy_bZS.mjs:1:789)
    at resolve (/Users/--/node_modules/tsx/dist/register-CCR7NebB.cjs:2:554)
    at resolveRequest (/Users/--/node_modules/tsx/dist/register-CCR7NebB.cjs:1:2758)
    at Function._resolveFilename (/Users/--/node_modules/tsx/dist/register-CCR7NebB.cjs:2:583)
    at Module._load (node:internal/modules/cjs/loader:1045:27) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v22.4.0
```

I am running this on an intel mac

```
sw_vers                                                                                                   
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
```

Here is my example .ts

```typescript

import fs from "node:fs/promises";
import { Document, VectorStoreIndex } from "llamaindex";

async function main() {
  // Load essay from abramov.txt in Node
  const essay = await fs.readFile(
    "node_modules/llamaindex/examples/abramov.txt",
    "utf-8",
  );

  // Create Document object with essay
  const document = new Document({ text: essay });

  // Split text and create embeddings. Store them in a VectorStoreIndex
  const index = await VectorStoreIndex.fromDocuments([document]);

  // Query the index
  const queryEngine = index.asQueryEngine();
  const response = await queryEngine.query({
    query: "What did the author do in college?",
  });

  // Output response
  console.log(response.toString());
}

main();
```

My tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "esnext",
    "moduleResolution": "bundler",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "lib": [
      "ES2022"
    ],
    "types": [
      "node"
    ],
    "outDir": "./lib",
    "tsBuildInfoFile": "./lib/.tsbuildinfo",
    "incremental": true,
    "composite": true
  },
  "ts-node": {
    "files": true,
    "compilerOptions": {
      "module": "commonjs"
    }
  },
  "include": [
    "./**/*.ts"
  ]
}
```

And package.json

```json
{
  "name": "sample",
  "version": "1.0.0",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "llamaindex": "^0.4.11"
  },
  "devDependencies": {
    "@types/node": "^20.14.9",
    "tsx": "^4.16.2",
    "typescript": "^5.5.3"
  }
}

```

**Comment by himself65** [comment]
same issue with https://github.com/run-llama/LlamaIndexTS/issues/1012

**Comment by himself65** [comment]
Please check 0.4.12
