### ISSUE TITLE
npx create-llama is producing bugged apps

### ISSUE THREAD

**Issue by Arputikos** [run-llama/LlamaIndexTS#1075]
The command "npx create-llama@latest" is creating bugged apps. (Probably next.js frontend bug - both next.js and python backend versions produce the error)
Reproduction:
Create app with that command and following settings:

>  Which template would you like to use? » Agentic RAG (single agent)
> √ Which framework would you like to use? » FastAPI (Python)
> √ Would you like to generate a NextJS frontend for your FastAPI (Python) backend? ... No / Yes
> √ Would you like to set up observability? » No
> √ Please provide your OpenAI API key (leave blank to skip): ... sk-proj-20hNz4BZK1S6QjCBKdsUT3BlbkFJ4yaaSAef1yT3Y47b7nyf
> √ Which data source would you like to use? » Use an example PDF
> √ Would you like to add another data source? » No
> √ Would you like to use LlamaParse (improved parser for RAG - requires API key)? ... no / yes
> √ Would you like to use a vector database? » No, just store the data in the file system
> √ Would you like to build an agent using tools? If so, select the tools here, otherwise just press enter » Weather
> √ How would you like to proceed? » Generate code, install dependencies, and run the app (~2 min)

then next.js frontend will throw following error:
⨯ TypeError: Promise.withResolvers is not a function
    at __webpack_require__ (C:\app\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (C:\app\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (C:\app\.next\server\webpack-runtime.js:33:42)
    at eval (./app/components/ui/chat/widgets/PdfDialog.tsx:8:80)
    at (ssr)/./app/components/ui/chat/widgets/PdfDialog.tsx (C:\app\.next\server\app\page.js:459:1)
    at __webpack_require__ (C:\app\.next\server\webpack-runtime.js:33:42)
    at eval (./app/components/ui/chat/chat-message/chat-sources.tsx:14:76)
    at (ssr)/./app/components/ui/chat/chat-message/chat-sources.tsx (C:\app\.next\server\app\page.js:338:1)
    at __webpack_require__ (C:\app\.next\server\webpack-runtime.js:33:42)
    at eval (./app/components/ui/chat/chat-message/index.tsx:18:71)
    at (ssr)/./app/components/ui/chat/chat-message/index.tsx (C:\app\.next\server\app\page.js:382:1)
    at __webpack_require__ (C:\app\.next\server\webpack-runtime.js:33:42)
    at eval (./app/components/ui/chat/chat-messages.tsx:12:71)
    at (ssr)/./app/components/ui/chat/chat-messages.tsx (C:\app\.next\server\app\page.js:404:1)
    at __webpack_require__ (C:\app\.next\server\webpack-runtime.js:33:42)
    at eval (./app/components/ui/chat/index.ts:9:72)
    at (ssr)/./app/components/ui/chat/index.ts (C:\app\.next\server\app\page.js:448:1)
    at __webpack_require__ (C:\app\.next\server\webpack-runtime.js:33:42)
    at eval (./app/components/chat-section.tsx:8:66)
    at (ssr)/./app/components/chat-section.tsx (C:\app\.next\server\app\page.js:250:1)
    at Object.__webpack_require__ [as require] (C:\app\.next\server\webpack-runtime.js:33:42)
digest: "1927380740"
 GET / 500 in 90ms

Happens on windows 11 x64

**Comment by marcusschiesser** [comment]
Sorry for the trouble fixed in create-llama@0.1.22

**Comment by marcusschiesser** [comment]
@Arputikos please revoke your OpenAI key posted above
