### ISSUE TITLE
Bundling issues with tiktoken (Error: Missing tiktoken_bg.wasm)

### ISSUE THREAD

**Issue by marcusschiesser** [run-llama/LlamaIndexTS#1127]
I am opening this ticket to gather all issues related to bundling the WASM from https://github.com/dqbd/tiktoken:

1. Using AWS Nodejs serverless project, see https://github.com/run-llama/LlamaIndexTS/issues/1110#issuecomment-2282274361
2. Using NextJS deploying on Vercel, see https://github.com/run-llama/create-llama/issues/164 (was fixed by copying the WASM file; see https://github.com/run-llama/create-llama/pull/201/files)

If you encounter this issue, please post your setup and configuration here.

**Comment by AndreMaz** [comment]
Just in case someone also faces the same issue. This is how I solved the issue

My `next.config.mjs`
```js
import path from "path";
import { fileURLToPath } from "url";
import _jiti from "jiti";

import { withLlamaIndex } from "@web/chatbot/next";

const jiti = _jiti(fileURLToPath(import.meta.url));

// Import env files to validate at build time. Use jiti so we can load .ts files in here.
jiti("./src/env");

const isStaticExport = "false";

// Get __dirname equivalent for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * @type {import("next").NextConfig}
 */
const nextConfig = {
  basePath: process.env.NEXT_PUBLIC_BASE_PATH,
  serverRuntimeConfig: {
    PROJECT_ROOT: __dirname,
  },
  env: {
    BUILD_STATIC_EXPORT: isStaticExport,
  },
  // Trailing slashes must be disabled for Next Auth callback endpoint to work
  // https://stackoverflow.com/a/78348528
  trailingSlash: false,
  modularizeImports: {
    "@mui/icons-material": {
      transform: "@mui/icons-material/{{member}}",
    },
    "@mui/material": {
      transform: "@mui/material/{{member}}",
    },
    "@mui/lab": {
      transform: "@mui/lab/{{member}}",
    },
  },
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"],
    });

    // To allow chatbot to work
    // Extracted from: https://github.com/neondatabase/examples/blob/main/ai/llamaindex/rag-nextjs/next.config.mjs
    config.resolve.alias = {
      ...config.resolve.alias,
      sharp$: false,
      "onnxruntime-node$": false,
    };

    // From: https://github.com/dqbd/tiktoken?tab=readme-ov-file#nextjs
    config.experiments = {
      asyncWebAssembly: true,
      layers: true,
    };

    return config;
  },
  ...(isStaticExport === "true" && {
    output: "export",
  }),

  experimental: {
    outputFileTracingIncludes: {
      "/*": ["./cache/**/*"],
      "/api/**/*": ["./node_modules/**/*.wasm"],
    },
    serverComponentsExternalPackages: ["tiktoken", "onnxruntime-node"],
  },

  /** Enables hot reloading for local packages without a build step */
  transpilePackages: [
    "@web/api",
    "@web/auth",
    "@web/db",
    "@web/ui",
    "@web/validators",
    "@web/services",
    "@web/utils",
    "@web/logger",
    "@web/certs",
    "@web/chatbot",
  ],
  /** We already do linting and typechecking as separate tasks in CI */
  eslint: { ignoreDuringBuilds: true },
  typescript: { ignoreBuildErrors: true },
};

const withLlamaIndexConfig = withLlamaIndex(nextConfig);

export default withLlamaIndexConfig;
```

In my case everything related to `llamaindex` is at package `@web/chatbot`. This is why even the `withLlamaIndex` is being imported from `@web/chatbot/next`

Here's how my package.json at @web/chatbot looks like:
```json
{
  "name": "@web/chatbot",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "exports": {
    ".": "./src/index.ts",
    "./next": "./src/with-lama-index.mjs"
  },
  "license": "MIT",
  "scripts": {
    "clean": "rm -rf .turbo node_modules",
    "format": "prettier --check . --ignore-path ../../.gitignore --ignore-path ../../.prettierignore",
    "lint": "eslint .",
    "typecheck": "tsc --emitDeclarationOnly"
  },
  "devDependencies": {
    "@web/eslint-config": "workspace:*",
    "@web/prettier-config": "workspace:*",
    "@web/tsconfig": "workspace:*",
    "@web/utils": "workspace:*",
    "eslint": "catalog:",
    "prettier": "catalog:",
    "typescript": "catalog:"
  },
  "prettier": "@web/prettier-config",
  "dependencies": {
    "@web/logger": "workspace:*",
    "@t3-oss/env-nextjs": "catalog:",
    "js-tiktoken": "^1.0.14",
    "llamaindex": "catalog:",
    "pg": "^8.13.0",
    "tiktoken": "^1.0.16"
  }
}
```

For reference: The `next.config.mjs` and my repo struct is based on [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo) repo

**Comment by mrsamirr** [comment]
#164

**Comment by mobob** [comment]
I think i'm a victim of this too! My lamba logs (sorry, these ones are minified):

```
app-logs        | 2024-10-09T03:02:44 {"timestamp":"2024-10-09T03:02:44.451Z","level":"ERROR","message":{"errorType":"Error","errorMessage":"Missing tiktoken_bg.wasm","stackTrace":["Error: Missing tiktoken_bg.wasm","    at node_modules/.pnpm/tiktoken@1.0.17/node_modules/tiktoken/tiktoken.cjs (/var/task/index.js:137027:13)","    at __require2 (/var/task/index.js:18:53)","    at node_modules/.pnpm/@llamaindex+env@0.1.13_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1._d65gjdt6k6tmj5pmt5qhv3yqf4/node_modules/@llamaindex/env/dist/tokenizers/node.js (/var/task/index.js:137043:32)","    at __init (/var/task/index.js:15:59)","    at node_modules/.pnpm/@llamaindex+env@0.1.13_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1._d65gjdt6k6tmj5pmt5qhv3yqf4/node_modules/@llamaindex/env/dist/index.js (/var/task/index.js:137131:5)","    at __init (/var/task/index.js:15:59)","    at node_modules/.pnpm/@llamaindex+core@0.2.11_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1_333vhfcqr2gqzir7ihb4nbnsrq/node_modules/@llamaindex/core/agent/dist/index.js (/var/task/index.js:141039:5)","    at __init (/var/task/index.js:15:59)","    at node_modules/.pnpm/@llamaindex+openai@0.1.14_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_encoding@0._oeg7rmwedn7wy56dfzvlejhd6a/node_modules/@llamaindex/openai/dist/index.js (/var/task/index.js:147568:5)","    at __init (/var/task/index.js:15:59)"]}}
```

My stack is;
- pnpm monorepo, mostly typescript within (note - have had issues with this setup too as i've needed to install some stuff at project root for ...  some reason!)
- all deployed to AWS via CDK, lambdas running node18 i believe
- recently moved to LlamaIndex to parse PDFs and have been grappling with bizarre dep issues all day

I think this is the last workaround and things seem to be ok now. Most recent issue was on lambda execute, i'd get the above error, long before llamaindex was being used. I'm no bundling expert, but i believe one equivalent workaround of the next js workaround that i think is working for me is to install vs bundle tiktoken via an esbuild option, which i have no idea how it will slow things down. 

```typescript

const settings : cdk.aws_lambda_nodejs.NodejsFunctionProps = {
    handler: "handler",
    runtime: props.serviceConfig.nodeRuntime,
    memorySize: 256,
    tracing: Tracing.ACTIVE,
    bundling: {
      logLevel: LogLevel.INFO,

      nodeModules: ["tiktoken"], // main workaround

      minify: false, //branchIsMain(), tried both
      tsconfig: "../backend/tsconfig.json",

      sourceMap: !branchIsMain(),
      metafile: !branchIsMain(),

      // TODO LlamaIndex hack - see https://github.com/evanw/esbuild/issues/1051
      // this might appear as the following error during synth: No loader is configured for ".node" files: node_modules/.pnpm/onnxruntime-node
      loader: {
        // i needed to add this for another llamaindex dep issue
        ".node": "file",
        // i had this briefly, but now that its installed i don't need it anymore
        // ".wasm": "file",
      },
    },
  };
```

Would love some wisdom on this workaround, and if there are plans to fix this. I'd also love some insight about if i really should need to install some of these extra libs in my package.json, as i obviously went ahead and did that but it often didn't have an effect (i'll assume because they were all shaken out). Thanks for tracking this!

**Comment by mobob** [comment]
Just a note; i was excited by @himself65's merge. I'm now getting this in my env on 0.7.7 during my bundle/synth phase:

```
✘ [ERROR] No matching export in "node_modules/.pnpm/@llamaindex+env@0.1.15_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_gpt-tokenizer@_knm3gj4fyseqd4vsl5w3q7owja/node_modules/@llamaindex/env/dist/index.js" for import "process"

    node_modules/.pnpm/@llamaindex+openai@0.1.21_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_encoding@0._2waopf2os4iylcfewklxyspmee/node_modules/@llamaindex/openai/dist/index.js:6:17:
      6 │ import { getEnv, process, Tokenizers } from '@llamaindex/env';
```
      
Using 0.7.5 bundles correctly, but at runtime there is some strange esm createRequire error and the lambda can't even get off the ground:

```
restapi           | 2024-10-24T13:02:58 {"timestamp":"2024-10-24T13:02:58.834Z","level":"ERROR","message":{"errorType":"TypeError","errorMessage":"The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined","stackTrace":["TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined","    at Function.createRequire (node:internal/modules/cjs/loader:1631:11)","    at Object.<anonymous> (/var/task/index.js:411433:28)","    at Module._compile (node:internal/modules/cjs/loader:1469:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)","    at Module.load (node:internal/modules/cjs/loader:1288:32)","    at Module._load (node:internal/modules/cjs/loader:1104:12)","    at Module.require (node:internal/modules/cjs/loader:1311:19)","    at require (node:internal/modules/helpers:179:18)","    at _tryRequireFile (file:///var/runtime/index.mjs:1002:37)","    at _tryRequire (file:///var/runtime/index.mjs:1052:25)"],"code":"ERR_INVALID_ARG_VALUE"}}
```

If anyone has hints on workarounds for the above i'll happily try, or spin a new issue. Otherwise i'll stick with the older tiktoken and try again in a few versions.

**Comment by himself65** [comment]
will check this

**Comment by himself65** [comment]
seems like bunchee have some dirty output

**Comment by himself65** [comment]
Might be related to https://github.com/huozhi/bunchee/issues/564
