### ISSUE TITLE
SyntaxError: The requested module '@llamaindex/env' does not provide an export named 'consoleLogger'

### ISSUE THREAD

**Issue by parhammmm** [run-llama/LlamaIndexTS#1266]
Something changed last week (happening in 0.6.10) and now when building llamaindex for Azure functions with the tsconfig bellow I get the error in the title, any ideas?

```ts
{
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": ".",
    "baseUrl": "./",
    "sourceMap": true,
    "target": "es6",
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "isolatedModules": true,
    "paths": {
      "@/*": ["./*"]
    },
    "types": ["vitest/globals"]
  },
  "tsc-alias": {
    "resolveFullPaths": true,
    "verbose": false
  },
  "include": ["src/", "__tests__"]
}
```

**Comment by huxhamd** [comment]
Same issue, but different stack.

Problem presents in an otherwise empty SvelteKit project.

Steps to repro.

`npm create svelte@latest broken-llamaindex`
When prompted for project options choose:
* Skeleton project
* Typescript (with typescript syntax)
* ESLint, Prettier
`cd broken-llamaindex`
`npm install`
`npm i llamaindex@0.6.10`

Start the app in local:
`npm run dev -- --open`

You will see the template works as expected with the default message "Welcome to SvelteKit"

Create a new file: ./src/routes/+page.server.ts

File contents:
`import { Document } from 'llamaindex';`

Page displays "500 | Internal Error"

Console errors with:
```
18:38:53 [vite] Error when evaluating SSR module /src/routes/+page.server.ts: failed to import "llamaindex"
|- file:///C:/Users/DanielHuxham/source/repos/test/node_modules/@llamaindex/core/agent/dist/index.js:1
import { emptyLogger, consoleLogger, randomUUID } from '@llamaindex/env';
                      ^^^^^^^^^^^^^
SyntaxError: The requested module '@llamaindex/env' does not provide an export named 'consoleLogger'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async nodeImport (file:///C:/Users/DanielHuxham/source/repos/test/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52999:15)
    at async ssrImport (file:///C:/Users/DanielHuxham/source/repos/test/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:16)
    at async eval (C:/Users/DanielHuxham/source/repos/test/src/routes/+page.server.ts:3:44)
    at async instantiateModule (file:///C:/Users/DanielHuxham/source/repos/test/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:5)

file:///C:/Users/DanielHuxham/source/repos/test/node_modules/@llamaindex/core/agent/dist/index.js:1
import { emptyLogger, consoleLogger, randomUUID } from '@llamaindex/env';
                      ^^^^^^^^^^^^^
SyntaxError: The requested module '@llamaindex/env' does not provide an export named 'consoleLogger'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async nodeImport (file:///C:/Users/DanielHuxham/source/repos/test/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52999:15)
    at async ssrImport (file:///C:/Users/DanielHuxham/source/repos/test/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52857:16)
    at async eval (C:/Users/DanielHuxham/source/repos/test/src/routes/+page.server.ts:3:44)
    at async instantiateModule (file:///C:/Users/DanielHuxham/source/repos/test/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:52915:5)
```

Importing anything from the llamaindex library results in the same error.

**Comment by himself65** [comment]
Forget to release a new version :(

I need update changeset
