### ISSUE TITLE
OPENAI_API_KEY required when not using OpenAI since update

### ISSUE THREAD

**Issue by bennyschmidt** [run-llama/LlamaIndexTS#1277]
Here's how I have been instantiating a vector store using `fromDocuments` for ~6 months without issues:

```javascript
    const index = await VectorStoreIndex.fromDocuments(
      [document],
      {
        serviceContext: {
          llm: new Ollama({
            model: 'mistral'
          }),
          embedModel: new OllamaEmbedding({
            model: 'mistral' 
          }),
          promptHelper: new PromptHelper(),
          nodeParser: new SimpleNodeParser(),
          callbackManager: new CallbackManager()
        }
      }
    );
```

But when I updated llamaindexTS recently, I now get the dreaded:

```
Error: Set OpenAI Key in OPENAI_API_KEY env variable
    at new OpenAISession
```

Why?

https://github.com/run-llama/LlamaIndexTS/blame/f7b4e94231626f2dfb0f2b4edc2cb684b9e8b974/packages/llamaindex/src/internal/settings/EmbedModel.ts#L10

This code compiles to the following JavaScript:

```javascript
let globalEmbeddedModel = null;

export function getEmbeddedModel() {
    if (globalEmbeddedModel === null) {
        globalEmbeddedModel = new OpenAIEmbedding();
    }
...

```

`globalEmbeddedModel` is always `null` so it always gets set to `OpenAIEmbedding` even if you aren't using OpenAI and even if you provide a service context.

I wanted to open a PR to fix it myself, but there were some architectural changes in that blamed PR that I don't quite understand, namely - why is a `StorageContext` required when I am not using storage?

The only reason OpenAI is being defaulted here is that `storageContextFromDefaults` is being called, but only because I don't provide one (never have). I have always used the in-memory vector store, and never had to provide a storage context.

@logan-markewich @marcusschiesser Any help would be highly appreciated thank you!

**Comment by himself65** [comment]
This is a bug since we are depracing the context service in the future and use `Settings.xxx` instead. I think context is missing when passing into the deep class or method

**Comment by himself65** [comment]
Could please provide more stack trace so I know where it's missing?

**Comment by bennyschmidt** [comment]
> Could please provide more stack trace so I know where it's missing?

Here's the trace after calling the above `fromDocuments`:

```
Error: Set OpenAI Key in OPENAI_API_KEY env variable
    at new OpenAISession (/home/benny/Documents/Projects/ragdoll/node_modules/@llamaindex/openai/dist/index.cjs:512:23)
    at getOpenAISession (/home/benny/Documents/Projects/ragdoll/node_modules/@llamaindex/openai/dist/index.cjs:534:19)
    at new OpenAIEmbedding (/home/benny/Documents/Projects/ragdoll/node_modules/@llamaindex/openai/dist/index.cjs:986:45)
    at getEmbeddedModel (/home/benny/Documents/Projects/ragdoll/node_modules/llamaindex/dist/cjs/internal/settings/EmbedModel.js:28:31)
    at new VectorStoreBase (/home/benny/Documents/Projects/ragdoll/node_modules/llamaindex/dist/cjs/vector-store/types.js:62:74)
    at new SimpleVectorStore (/home/benny/Documents/Projects/ragdoll/node_modules/llamaindex/dist/cjs/vector-store/SimpleVectorStore.js:98:9)
    at storageContextFromDefaults (/home/benny/Documents/Projects/ragdoll/node_modules/llamaindex/dist/cjs/storage/StorageContext.js:24:70)
    at VectorStoreIndex.fromDocuments (/home/benny/Documents/Projects/ragdoll/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:122:107)
```

seems like it tries to `storageContextFromDefaults` when one is not passed
