### ISSUE TITLE
"Number must be greater than 0" Errors

### ISSUE THREAD

**Issue by santsys** [run-llama/LlamaIndexTS#1296]
Hello! I'm likely doing something wrong here, but, trying to work through a sample application that is processing a single small document and then querying the index for information. I'm attempting to do this all locally using `Ollama` - but I have not been able to to get past this set of errors.

Any ideas or suggestions on what to try?

```
Number must be greater than 0 (["chunkSize"])
Number must be greater than or equal to 0 (["chunkOverlap"])
Chunk overlap must be less than chunk size. ([])
```

Running this in `Node v22.9.0`.

*Example code:*

```ts
import {
    Settings,
    Ollama,
    VectorStoreIndex,
    SimpleDirectoryReader,
    OllamaEmbedding,
} from 'llamaindex'

const MODEL_NAME = 'llama3.2'
const ollama = new Ollama({
    model: MODEL_NAME,
    config: {},
    options: { temperature: 0.5 },
})
const embedModel = new OllamaEmbedding({
    model: 'mxbai-embed-large',
    options: { temperature: 0.5 },
})

Settings.llm = ollama
Settings.embedModel = embedModel

async function main() {
    const dataDocs = await new SimpleDirectoryReader().loadData({
        directoryPath: './data',
    })

    console.log(`Loaded ${dataDocs.length} doument(s).`)

    const index = await VectorStoreIndex.fromDocuments(dataDocs, {
        logProgress: true,
    })
    const retriever = index.asRetriever()
    const queryEngine = index.asQueryEngine({
        retriever: retriever,
    })
    const stream = await queryEngine.query({
        query: '{{Question}}',
        stream: true,
    })

    for await (const chunk of stream) {
        process.stdout.write(chunk.delta)
    }
}
main().catch((e) => console.error(e))
```

```
Using node parser on documents...
Finished parsing documents.
getting embedding progress: 0 / 1
ZodError: [
  {
    "code": "too_small",
    "minimum": 0,
    "type": "number",
    "inclusive": false,
    "exact": false,
    "message": "Number must be greater than 0",
    "path": [
      "chunkSize"
    ]
  },
  {
    "code": "too_small",
    "minimum": 0,
    "type": "number",
    "inclusive": true,
    "exact": false,
    "message": "Number must be greater than or equal to 0",
    "path": [
      "chunkOverlap"
    ]
  },
  {
    "code": "custom",
    "message": "Chunk overlap must be less than chunk size.",
    "path": []
  }
]
    at get error (file:///./node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/index.mjs:587:31)
    at ZodEffects.parse (file:///./node_modules/.pnpm/zod@3.23.8/node_modules/zod/lib/index.mjs:692:22)      
    at new SentenceSplitter (file:///./node_modules/.pnpm/@llamaindex+core@0.2.8_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1._bmi77gdnidaxf3lqzmibpj7squ/node_modules/@llamaindex/core/node-parser/dist/index.js:318:57)
    at PromptHelper.getTextSplitterGivenPrompt (file:///./node_modules/.pnpm/@llamaindex+core@0.2.8_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1._bmi77gdnidaxf3lqzmibpj7squ/node_modules/@llamaindex/core/indices/dist/index.js:72:16)
    at PromptHelper.repack (file:///./node_modules/.pnpm/@llamaindex+core@0.2.8_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1._bmi77gdnidaxf3lqzmibpj7squ/node_modules/@llamaindex/core/indices/dist/index.js:82:35)      
    at CompactAndRefine.getResponse (file:///./node_modules/.pnpm/@llamaindex+core@0.2.8_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1._bmi77gdnidaxf3lqzmibpj7squ/node_modules/@llamaindex/core/response-synthesizers/dist/index.js:209:44)
    at CompactAndRefine.synthesize (file:///./node_modules/.pnpm/@llamaindex+core@0.2.8_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1._bmi77gdnidaxf3lqzmibpj7squ/node_modules/@llamaindex/core/response-synthesizers/dist/index.js:31:35)
    at RetrieverQueryEngine._query (file:///./node_modules/.pnpm/llamaindex@0.6.13_@aws-sdk+client-sso-oidc@3.662.0_@aws-sdk+client-sts@3.662.0__@aws-sdk+cred_ottdx7krjsm3z4s7c6pq2277m4/node_modules/llamaindex/dist/engines/query/RetrieverQueryEngine.js:15:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async RetrieverQueryEngine.query (file:///./node_modules/.pnpm/@llamaindex+core@0.2.8_@aws-crypto+sha256-js@5.2.0_@xenova+transformers@2.17.2_js-tiktoken@1._bmi77gdnidaxf3lqzmibpj7squ/node_modules/@llamaindex/core/query-engine/dist/index.js:405:26)
    at async main (C:\Depot\AI\mtg-processor\index.ts:69:20) {
  issues: [
    {
      code: 'too_small',
      minimum: 0,
      type: 'number',
      inclusive: false,
      exact: false,
      message: 'Number must be greater than 0',
      path: [Array]
    },
    {
      code: 'too_small',
      minimum: 0,
      type: 'number',
      inclusive: true,
      exact: false,
      message: 'Number must be greater than or equal to 0',
      path: [Array]
    },
    {
      code: 'custom',
      message: 'Chunk overlap must be less than chunk size.',
      path: []
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'too_small',
      minimum: 0,
      type: 'number',
      inclusive: false,
      exact: false,
      message: 'Number must be greater than 0',
      path: [Array]
    },
    {
      code: 'too_small',
      minimum: 0,
      type: 'number',
      inclusive: true,
      exact: false,
      message: 'Number must be greater than or equal to 0',
      path: [Array]
    },
    {
      code: 'custom',
      message: 'Chunk overlap must be less than chunk size.',
      path: []
    }
  ]
}
```

**Comment by himself65** [comment]
This is werid, I can run it successfully. Make sure `./data` directory load document successfully

**Comment by himself65** [comment]
Oh, i see the error when there's only one document

**Comment by himself65** [comment]
I can see the problem here is context size is even smaller than prompt length size

**Comment by himself65** [comment]
Please set `num_ctx` to the correct value, because we cannot help you to get the correct llm metadata

```
const ollama = new Ollama({
	model: MODEL_NAME,
	config: {},
	options: {
		temperature: 0.5,
	  num_ctx: 128_000,
	},
})
```

**Comment by santsys** [comment]
I seem to get the same error with more than one document and longer documents. It seems like the chunk size and chunk overlap are being seen as zero (or not set), but I'm not sure why.

**Comment by santsys** [comment]
> Please set `num_ctx` to the correct value, because we cannot help you to get the correct llm metadata

I set this, and it gives the same results.

**Comment by himself65** [comment]
> I set this, and it gives the same results.

So the reason is from loader side, you might load a too large content into one Document.

You can run text spliiter after load the document

```
const dataDocs = await new SimpleDirectoryReader().loadData({
  directoryPath: './empty',
})
const textSplitter = new SentenceSplitter()
const docs = await textSplitter(dataDocs)
```

**Comment by santsys** [comment]
> So the reason is from loader side, you might load a too large content into one Document.

This document is short (4kb). The loader code seems to run fine but fails after it requests embeddings (though embeddings return manually if i pass the content to Ollama manually via API.

<img width="770" alt="image" src="https://github.com/user-attachments/assets/60c0c01c-33cd-4377-95af-01ad286d5e1e">

**Comment by santsys** [comment]
Updated to `llamaindex v0.6.15` and still encounter the same errors.

**Comment by santsys** [comment]
I set this up to store the index to disk and the system is generating what appears to be valid vector stores, etc. `doc_store.json`, `index_store.json`, and `vector_store.json` all get populated. But running an actual query still fails with the same errors.

**Comment by santsys** [comment]
From what I've been able to figure out so far is it appears there is a `SentenceSplitter` getting setup somewhere that is missing or has bad configuration... But I'm not specifically sure where that is happening inside of the query chain. But calling query on an index fails before making a call to the LLM - so it seems like an internal Llamaindex configuration issue.

**Comment by pyxis777** [comment]
I'm also having the same issue with Ollama.  My goal is to use Ollama and local embeddings instead of OpenAI  

Code: 
```
import fs from "node:fs/promises";

import {
  Document,
  MetadataMode,
  NodeWithScore,
  VectorStoreIndex,
  Ollama,
  OllamaEmbedding,
  Settings,
  HuggingFaceEmbedding,
  OpenAI
} from "llamaindex";

const MODEL_NAME = 'llama3';

const ollama = new Ollama({ model: "llama3" });
const embedModel = new HuggingFaceEmbedding({
  modelType: "BAAI/bge-small-en-v1.5",
  quantized: false,
});

Settings.llm = ollama;
Settings.embedModel = embedModel;

async function main() {
  // Load essay from abramov.txt in Node
  const path = "node_modules/llamaindex/examples/abramov.txt";

  const essay = await fs.readFile(path, "utf-8");

  // Create Document object with essay
  const document = new Document({ text: essay, id_: path });

  // Split text and create embeddings. Store them in a VectorStoreIndex
  const index = await VectorStoreIndex.fromDocuments([document]);

  // Query the index
  const queryEngine = index.asQueryEngine();
  const { response, sourceNodes } = await queryEngine.query({
    query: "What did the author do in college?",
  });

  // Output response with sources
  console.log(response);

  if (sourceNodes) {
    sourceNodes.forEach((source: NodeWithScore, index: number) => {
      console.log(
        `\n${index}: Score: ${source.score} - ${source.node.getContent(MetadataMode.NONE).substring(0, 50)}...\n`,
      );
    });
  }
}

main().catch(console.error);
```

I get this error
```
(node:38005) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ZodError: [
  {
    "code": "too_small",
    "minimum": 0,
    "type": "number",
    "inclusive": false,
    "exact": false,
    "message": "Number must be greater than 0",
    "path": [
      "chunkSize"
    ]
  },
  {
    "code": "too_small",
    "minimum": 0,
    "type": "number",
    "inclusive": true,
    "exact": false,
    "message": "Number must be greater than or equal to 0",
    "path": [
      "chunkOverlap"
    ]
  },
  {
    "code": "custom",
    "message": "Chunk overlap must be less than chunk size.",
    "path": []
  }
]
    at get error (LlamaIndexTS/node_modules/zod/lib/types.js:55:31)
    at ZodEffects.parse (LlamaIndexTS/node_modules/zod/lib/types.js:160:22)
    at new SentenceSplitter (LlamaIndexTS/node_modules/@llamaindex/core/node-parser/dist/index.cjs:320:67)
    at PromptHelper.getTextSplitterGivenPrompt (LlamaIndexTS/node_modules/@llamaindex/core/indices/dist/index.cjs:74:16)
    at PromptHelper.repack (LlamaIndexTS/node_modules/@llamaindex/core/indices/dist/index.cjs:84:35)
    at CompactAndRefine.getResponse (LlamaIndexTS/node_modules/@llamaindex/core/response-synthesizers/dist/index.cjs:211:44)
    at CompactAndRefine.synthesize (LlamaIndexTS/node_modules/@llamaindex/core/response-synthesizers/dist/index.cjs:33:35)
    at RetrieverQueryEngine._query (LlamaIndexTS/node_modules/llamaindex/dist/cjs/engines/query/RetrieverQueryEngine.js:30:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetrieverQueryEngine.query (LlamaIndexTS/node_modules/@llamaindex/core/query-engine/dist/index.cjs:407:26)
    at main (LlamaIndexTS/main.ts:54:37) {
  issues: [
    {
      code: 'too_small',
      minimum: 0,
      type: 'number',
      inclusive: false,
      exact: false,
      message: 'Number must be greater than 0',
      path: [Array]
    },
    {
      code: 'too_small',
      minimum: 0,
      type: 'number',
      inclusive: true,
      exact: false,
      message: 'Number must be greater than or equal to 0',
      path: [Array]
    },
    {
      code: 'custom',
      message: 'Chunk overlap must be less than chunk size.',
      path: []
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'too_small',
      minimum: 0,
      type: 'number',
      inclusive: false,
      exact: false,
      message: 'Number must be greater than 0',
      path: [Array]
    },
    {
      code: 'too_small',
      minimum: 0,
      type: 'number',
      inclusive: true,
      exact: false,
      message: 'Number must be greater than or equal to 0',
      path: [Array]
    },
    {
      code: 'custom',
      message: 'Chunk overlap must be less than chunk size.',
      path: []
    }
  ]
}

```

Everything works fine when I use OpenAI as the model instead an Ollama model
```
const openai = new OpenAI({ model: "gpt-3.5-turbo", temperature: 0 });

const embedModel = new HuggingFaceEmbedding({
  modelType: "BAAI/bge-small-en-v1.5",
  quantized: false,
});

Settings.llm = openai
Settings.embedModel = embedModel
```

**Comment by himself65** [comment]
working on it
