### ISSUE TITLE
Documents excluding PDF are throwing an error in LlamaParse

### ISSUE THREAD

**Issue by LawrenceGB** [run-llama/LlamaIndexTS#1302]
Using the LlamaCloud parser only works with PDFs and Images. If I upload a docx, txt etc it throws this error.

It should be agnostic and should work for these types also I believe?

```
Error: Failed to parse the file: c175a7e7-edbb-4287-9d3d-b0ca4b288d4b, status: ERROR
>      at LlamaParseReader.getJobResult (/Users/lg/Documents/code/contacted/backend/functions/node_modules/@llamaindex/cloud/reader/dist/index.cjs:597:23)
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>      at async LlamaParseReader.loadJson (/Users/lg/Documents/code/contacted/backend/functions/node_modules/@llamaindex/cloud/reader/dist/index.cjs:650:32)
>      at async pdfHandler (/Users/lg/Documents/code/contacted/backend/functions/src/endpoints/training/file-upload/index.js:89:22)
>      at async FileUpload (/Users/lg/Documents/code/contacted/backend/functions/src/endpoints/training/file-upload/index.js:294:77)
>      at async /Users/lg/Documents/code/contacted/backend/functions/src/routes/training.js:38:9
>      at async runFunction (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:9)
>      at async runCloudEvent (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:523:5)
>      at async /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:690:21

```

**Comment by ajpanyteam** [comment]
I reported a similar issue with PowerPoint files... https://github.com/run-llama/llama_parse/issues/431

**Comment by himself65** [comment]
I think this should be fixed
