### ISSUE TITLE
create-llama fastapi workflow not reading .env correctly....

### ISSUE THREAD

**Issue by rawwerks** [run-llama/LlamaIndexTS#210]
### Details

i'm following the workflow: 

<img width="458" alt="image" src="https://github.com/run-llama/LlamaIndexTS/assets/19483938/e83aa89b-748c-4a5b-b2f2-fe262be5b3e3">

i can see the `.env` file with the openai_api_key, in the /backend folder. but for some reason it's not finding it (after `poetry install`, `poetry shell`, `python main.py`) (error below)

i've tried 3 times in 3 different locations with create-llama, same error. even tried one with sudo in front of everything just in case it was a file permission issue, no dice.

```
Traceback (most recent call last):
  File "/Users/raw/Library/Caches/pypoetry/virtualenvs/llamaindex-fastapi-streaming-FzlxdCA4-py3.11/lib/python3.11/site-packages/llama_index/embeddings/utils.py", line 42, in resolve_embed_model
    validate_openai_api_key(embed_model.api_key)
  File "/Users/raw/Library/Caches/pypoetry/virtualenvs/llamaindex-fastapi-streaming-FzlxdCA4-py3.11/lib/python3.11/site-packages/llama_index/llms/openai_utils.py", line 371, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/raw/sudollama/backend/main.py", line 4, in <module>
    from app.api.routers.chat import chat_router
  File "/Users/raw/sudollama/backend/app/api/routers/chat.py", line 6, in <module>
    from app.utils.index import get_index
  File "/Users/raw/sudollama/backend/app/utils/index.py", line 17, in <module>
    service_context = ServiceContext.from_defaults(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/raw/Library/Caches/pypoetry/virtualenvs/llamaindex-fastapi-streaming-FzlxdCA4-py3.11/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 168, in from_defaults
    embed_model = resolve_embed_model(embed_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/raw/Library/Caches/pypoetry/virtualenvs/llamaindex-fastapi-streaming-FzlxdCA4-py3.11/lib/python3.11/site-packages/llama_index/embeddings/utils.py", line 44, in resolve_embed_model
    raise ValueError(
ValueError: 
******
Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

Consider using embed_model='local'.
Visit our documentation for more embedding options: https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#modules
******

```

<details open>
<summary>Checklist</summary>

- [X] Modify `packages/create-llama/templates/types/streaming/fastapi/main.py` ✓ https://github.com/run-llama/LlamaIndexTS/commit/55ecaaf99982eb07e030651b0ebaf38b94c3cbd4
- [X] Modify `packages/create-llama/templates/types/simple/fastapi/main.py` ✓ https://github.com/run-llama/LlamaIndexTS/commit/e1be338fdcc6fadde5b8a6d31f2e6fd95d0e32a9

![Flowchart](http://24.199.78.105:8082/public/dfab5f91a7de0b723d17f159bfb3ea960f509da3d6314eab3e08b7a29460da63_210_flowchart.svg)
</details>

**Comment by rawwerks** [comment]
what is interesting is that i don't have the problem with running just the next.js version (no python backend) - but that file is called `.env.local`

**Comment by rawwerks** [comment]
probably related to this: https://github.com/run-llama/LlamaIndexTS/pull/199/files/37b2678065a5c6c1b91f6053bd9b128e53856559

**Comment by logan-markewich** [comment]
Should be fixed in https://github.com/run-llama/LlamaIndexTS/pull/216
