### ISSUE TITLE
Build error needing webpack

### ISSUE THREAD

**Issue by Ahmed14z** [run-llama/LlamaIndexTS#301]
```$ next build && npm run seed
   ▲ Next.js 14.0.1
   - Environments: .env

Failed to compile.

./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/ sync ^\.\/.*\/.*\/onnxruntime_binding\.node$
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/binding.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/backend.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/index.js
./node_modules/@xenova/transformers/src/backends/onnx.js
./node_modules/@xenova/transformers/src/env.js
./node_modules/@xenova/transformers/src/transformers.js
./node_modules/llamaindex/dist/index.mjs
./app/chat/api/chat/route.ts

./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/darwin/x64/onnxruntime_binding.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/darwin/x64/onnxruntime_binding.node
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/ sync ^\.\/.*\/.*\/onnxruntime_binding\.node$
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/binding.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/backend.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/index.js
./node_modules/@xenova/transformers/src/backends/onnx.js
./node_modules/@xenova/transformers/src/env.js
./node_modules/@xenova/transformers/src/transformers.js
./node_modules/llamaindex/dist/index.mjs
./app/chat/api/chat/route.ts

./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/linux/arm64/onnxruntime_binding.node
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/linux/arm64/onnxruntime_binding.node
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/ sync ^\.\/.*\/.*\/onnxruntime_binding\.node$
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/binding.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/backend.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/index.js
./node_modules/@xenova/transformers/src/backends/onnx.js
./node_modules/@xenova/transformers/src/env.js
./node_modules/@xenova/transformers/src/transformers.js
./node_modules/llamaindex/dist/index.mjs
./app/chat/api/chat/route.ts

./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/linux/x64/onnxruntime_binding.node
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/linux/x64/onnxruntime_binding.node
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/ sync ^\.\/.*\/.*\/onnxruntime_binding\.node$
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/binding.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/backend.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/index.js
./node_modules/@xenova/transformers/src/backends/onnx.js
./node_modules/@xenova/transformers/src/env.js
./node_modules/@xenova/transformers/src/transformers.js
./node_modules/llamaindex/dist/index.mjs
./app/chat/api/chat/route.ts

./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/win32/arm64/onnxruntime_binding.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/win32/arm64/onnxruntime_binding.node
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/ sync ^\.\/.*\/.*\/onnxruntime_binding\.node$
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/binding.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/backend.js
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/index.js
./node_modules/@xenova/transformers/src/backends/onnx.js
./node_modules/@xenova/transformers/src/env.js
./node_modules/@xenova/transformers/src/transformers.js
./node_modules/llamaindex/dist/index.mjs
./app/chat/api/chat/route.ts


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
i get this error when i build while using llamaindex on Next , and i tried adding this next config :```
/** @type {import('next').NextConfig} */
// const nextConfig = {}

// module.exports = nextConfig

// next.config.js
module.exports = {
    webpack: (config, { isServer }) => {
      // Add a rule for handling binary files
      config.module.rules.push({
        test: /\.(node)$/,
        use: 'raw-loader',
      });
  
      return config;
    },
  };

then i got another error : ```
 Collecting page data  ..Error: ENOENT: no such file or directory, open './test/data/05-versions-space.pdf'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at 57910 (/Users/ahmedeslam/Desktop/client/.next/server/chunks/825.js:39:24232)
    at __webpack_require__ (/Users/client/.next/server/webpack-runtime.js:1:161)
    at 39232 (/Users/client/.next/server/chunks/825.js:115:1629)
    at __webpack_require__ (/Users//client/.next/server/webpack-runtime.js:1:161)
    at 91140 (/Users/ahmedeslam/Desktop//client/.next/server/app/chat/api/chat/route.js:1:2453)
    at __webpack_require__ (/Users/ahmedeslam/client/.next/server/webpack-runtime.js:1:161)
    at __webpack_exec__ (/Users/ahmedeslam/client/.next/server/app/chat/api/chat/route.js:9:697)
    at /Users/ahmedeslam/client/.next/server/app/chat/api/chat/route.js:9:728 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './test/data/05-versions-space.pdf'
}

> Build error occurred
Error: Failed to collect page data for /chat/api/chat
    at /Users/node_modules/next/dist/build/utils.js:1211:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
error Command failed with exit code 1.````

**Comment by Ahmed14z** [comment]
im sure im not referencing any 05-versions-space.pdf , so any idea what is this ?
