### ISSUE TITLE
HuggingFaceEmbedding not compatible with ChromaVectorStore / chromadb

### ISSUE THREAD

**Issue by ThaNarie** [run-llama/LlamaIndexTS#472]
After creating embeddings using `HuggingFaceEmbeddings`, and passing them to `ChromaVectorStore`, chromadb does a check to see if the passed embeddings area already nested arrays, and if not, it nests them:
https://github.com/chroma-core/chroma/blob/a370684dd032eaf52ad9619c4811449a52cc1e2c/clients/js/src/utils.ts#L7

However, since `HuggingFaceEmbeddings` returns the embeddings as a `Float32Array` instead of a normal `Array`, that check will "fail", and creates a double-nested array, resulting in the Error message: `Error: ids, embeddings, metadatas, and documents must all be the same length`

Changing https://github.com/run-llama/LlamaIndexTS/blob/24cb48f195338a3a89c405ded7b916313ad06d26/packages/core/src/embeddings/HuggingFaceEmbedding.ts#L42 to `return [...output.data];`, to return a normal array (like other embeddings like Ollama) seems to fix the issue.

**Comment by logan-markewich** [comment]
@ThaNarie I've never seen this before. Can you share some code to replicate?

As a reference, the example here uses huggingface embeddings with chroma 
https://docs.llamaindex.ai/en/stable/examples/vector_stores/ChromaIndexDemo.html#chroma

**Comment by ThaNarie** [comment]
Example code:

```js
import { ChromaVectorStore, HuggingFaceEmbedding, HuggingFaceEmbeddingModelType, Ollama, serviceContextFromDefaults, storageContextFromDefaults, VectorStoreIndex, SimpleDirectoryReader } from 'llamaindex';
import fs from 'node:fs/promises';

// storage
const vectorStore = new ChromaVectorStore({ collectionName: 'demo'});
const storageContext = await storageContextFromDefaults({
  vectorStore,
});

// service
const llm = new Ollama({
  model: 'llama2',
});
const embedModel = new HuggingFaceEmbedding({
  modelType: HuggingFaceEmbeddingModelType.XENOVA_ALL_MINILM_L6_V2
});
const serviceContext = serviceContextFromDefaults({
  llm, // this isn't used in this test, but if you don't pass, it complains about OPENAI_API_KEY not set
  embedModel,
  chunkSize: 256,
  chunkOverlap: 20,
});

// documents
const documents = await new SimpleDirectoryReader().loadData({
  directoryPath: './test-data',
  fs, // need to pass this explicitly, since the defaultFs is a SimpleMemoryStorage, which doesn't have readDir implemented
});
console.log(`Found ${documents.length} document chunks to index`);

// embed documents
await VectorStoreIndex.fromDocuments(documents, {
  storageContext,
  serviceContext,
  logProgress: true,
});
console.log(`Storage context successfully generated`);
```

Make sure you have at least 2 "nodes" being embedded.

```
Found 3 document chunks to index
Using node parser on documents...
Finished parsing documents.
Getting embedding for node 1/3
Getting embedding for node 2/3
Getting embedding for node 3/3
/Volumes/Projects/ai/llamaindex-server/node_modules/llamaindex/node_modules/chromadb/dist/chromadb.mjs:1790
      throw new Error(
            ^

Error: ids, embeddings, metadatas, and documents must all be the same length
    at Collection.validate (/node_modules/llamaindex/node_modules/chromadb/dist/chromadb.mjs:1790:13)
    at Collection.add (/node_modules/llamaindex/node_modules/chromadb/dist/chromadb.mjs:1828:84)
    at <anonymous> (/node_modules/llamaindex/index.mjs:4452:30)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$J (/node_modules/llamaindex/index.mjs:4391:28)
    at _next (/node_modules/llamaindex/index.mjs:4409:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by marcusschiesser** [comment]
@ThaNarie thanks for the bug report! Fixed in https://github.com/run-llama/LlamaIndexTS/pull/482 - please have a look
