### ISSUE TITLE
Error running 0.0.23: no such file or directory vectordbs/python

### ISSUE THREAD

**Issue by gbrian** [run-llama/LlamaIndexTS#506]
Hi,
Found this issue while running latest release 0.0.23

Running: `npx create-llama@latest`

```
Aborting installation.
Unexpected error. Please report it as a bug:
 Error: ENOENT: no such file or directory, scandir '/root/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/templates/components/vectordbs/python'
    at Object.readdirSync (node:fs:1547:3)
    at getVectorDbChoices (/root/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:298:20383)
    at askQuestions (/root/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:298:27091)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/root/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:298:31136) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/root/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/templates/components/vectordbs/python'
}
```

Switching to 0.0.22 works fine.

**Comment by ylhsieh** [comment]
I switched to 0.0.22 and faced another bug of 
```

**Comment by marcusschiesser** [comment]
Sorry, there was a problem with the template lookup, see https://github.com/run-llama/LlamaIndexTS/issues/499#issuecomment-1923466789
