### ISSUE TITLE
Error on Deno

### ISSUE THREAD

**Issue by himself65** [run-llama/LlamaIndexTS#599]
```tsx
import { OpenAI, SimpleChatEngine, SummaryChatHistory } from "@llamaindex/core";

async function main() {
  // Set maxTokens to 75% of the context window size of 4096
  // This will trigger the summarizer once the chat history reaches 25% of the context window size (1024 tokens)
  const llm = new OpenAI({ model: "gpt-3.5-turbo", maxTokens: 4096 * 0.75 });
  const chatHistory = new SummaryChatHistory({ llm });
  const chatEngine = new SimpleChatEngine({ llm });

  while (true) {
    const query = await prompt("Query");
    if (!query) {
      throw new Error("Query is required");
    }
    const stream = await chatEngine.chat({
      message: query,
      chatHistory,
      stream: true,
    });
    if (chatHistory.getLastSummary()) {
      // Print the summary of the conversation so far that is produced by the SummaryChatHistory
      console.log(`Summary: ${chatHistory.getLastSummary()?.content}`);
    }
		
    for await (const chunk of stream) {
			Deno.stdout.write(new TextEncoder().encode(chunk.toString()));
    }
    console.log();
  }
}

main().catch(console.error);
```

```shell
deno run main.ts
✅ Granted env access to "READABLE_STREAM".
✅ Granted read access to <main_module>.
✅ Granted env access to "FORCE_COLOR".
✅ Granted env access to "CI".
✅ Granted env access to "TEAMCITY_VERSION".
✅ Granted env access to "TERM_PROGRAM".
✅ Granted env access to "TERM_PROGRAM_VERSION".
✅ Granted all env access.
✅ Granted all read access.
TypeError: Cannot read properties of undefined (reading 'env')
    at shouldUseAzure (https://jsr.io/@llamaindex/core/0.1.19/src/llm/azure.ts:116:13)
    at new OpenAI (https://jsr.io/@llamaindex/core/0.1.19/src/llm/LLM.ts:127:24)
    at main (file:///Users/himself65/Code/test-deno-llamaindex/main.ts:6:15)
    at file:///Users/himself65/Code/test-deno-llamaindex/main.ts:32:1
```

There is no `process.env`, we need put them to other place

**Comment by himself65** [comment]
Hot fix:
```
globalThis.process = {
	env: {
		OPENAI_API_KEY: Deno.env.get("OPENAI_API_KEY") || "",
	}
}
```
