### ISSUE TITLE
Embedding length mismatch

### ISSUE THREAD

**Issue by abhim1509** [run-llama/LlamaIndexTS#895]
Hey, I am trying to run RAG pipeline privately with Ollama.

Here are config details:
1. Llamaindex: ^0.3.14
2. Ollama for Windows
3. LLM: Llama3
4. Embedding model: Hugging face model XENOVA_ALL_MPNET_BASE_V2

I am getting Embedding length mismatch error. Kindly help on the same.

**Comment by marcusschiesser** [comment]
@abhim1509 Can you please post a reproducible use case?

**Comment by himself65** [comment]
https://github.com/run-llama/LlamaIndexTS/blob/1b1081b9c9b03b23906fc3278d9172a681df00d9/packages/core/src/embeddings/utils.ts#L32

**Comment by siwin-anto** [comment]
I am also facing the error. the details of my code given below, 

In chat.ts file, i have written the below code, 

import { ContextChatEngine, Settings } from "llamaindex";
import { getDataSource } from "./index";

export async function createChatEngine(documentIds?: string[]) {
  const index = await getDataSource();
  if (!index) {
    throw new Error(
      StorageContext is empty - call 'npm run generate' to generate the storage first,
    );
  }

  const retriever = index.asRetriever({
    similarityTopK: process.env.TOP_K ? parseInt(process.env.TOP_K) : 3,
  });

  console.log("retriever:", retriever);

  return new ContextChatEngine({
    chatModel: Settings.llm,
    retriever,
    // disable as a custom system prompt disables the generated context
    // systemPrompt: process.env.SYSTEM_PROMPT,
  });
}


In setting.ts file, i have written the following function,

function initGemini() {
  Settings.llm = new Gemini({
    model: GEMINI_MODEL.GEMINI_PRO,
    session: new GeminiVertexSession({
      location: "us-central1",
      project: process.env.GOOGLE_VERTEX_PROJECT,
    }),
  });

  let stringifiedSystem = JSON.stringify(Settings.llm);
  console.log("LLM set:", stringifiedSystem);

  Settings.embedModel = new GeminiEmbedding({
    model: models/embedding-001 as GEMINI_EMBEDDING_MODEL,
  });

  console.log("Embedding model set:", JSON.stringify(Settings.embedModel));
}

i get the error as follows,

[LlamaIndex] Error: Embedding length mismatch
[1]     at similarity (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/@llamaindex/core/dist/embeddings/index.js:35:15)
[1]     at getTopKEmbeddings (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/internal/utils.js:40:21)
[1]     at SimpleVectorStore.query (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/storage/vectorStore/SimpleVectorStore.js:152:41)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async VectorIndexRetriever.retrieveQuery (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/indices/vectorStore/index.js:643:32)
[1]     at async VectorIndexRetriever.retrieve (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/indices/vectorStore/index.js:618:54)
[1]     at async DefaultContextGenerator.generate (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/engines/chat/DefaultContextGenerator.js:34:38)
[1]     at async ContextChatEngine.prepareRequestMessages (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/engines/chat/ContextChatEngine.js:451:25)
[1]     at async ContextChatEngine.chat (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/engines/chat/ContextChatEngine.js:418:33)


what might be the cause for this error and how should we fix this?

**Comment by siwin-anto** [comment]
i am also facing the same error. I have provided the details of the code given below,

In chat.ts file, i have written the below code, 

import { ContextChatEngine, Settings } from "llamaindex";
import { getDataSource } from "./index";

export async function createChatEngine(documentIds?: string[]) {
  const index = await getDataSource();
  if (!index) {
    throw new Error(
      StorageContext is empty - call 'npm run generate' to generate the storage first,
    );
  }

  const retriever = index.asRetriever({
    similarityTopK: 3,
  });

  console.log("retriever:", retriever);

  return new ContextChatEngine({
    chatModel: Settings.llm,
    retriever
  });
}


In setting.ts file, i have written the following function,

function initGemini() {
  Settings.llm = new Gemini({
    model: GEMINI_MODEL.GEMINI_PRO,
    session: new GeminiVertexSession({
      location: "us-central1",
      project: process.env.GOOGLE_VERTEX_PROJECT,
    }),
  });

  let stringifiedSystem = JSON.stringify(Settings.llm);
  console.log("LLM set:", stringifiedSystem);

  Settings.embedModel = new GeminiEmbedding({
    model: models/embedding-001 as GEMINI_EMBEDDING_MODEL,
  });

  console.log("Embedding model set:", JSON.stringify(Settings.embedModel));
}

i get the error as follows,

[LlamaIndex] Error: Embedding length mismatch
[1]     at similarity (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/@llamaindex/core/dist/embeddings/index.js:35:15)
[1]     at getTopKEmbeddings (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/internal/utils.js:40:21)
[1]     at SimpleVectorStore.query (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/storage/vectorStore/SimpleVectorStore.js:152:41)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async VectorIndexRetriever.retrieveQuery (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/indices/vectorStore/index.js:643:32)
[1]     at async VectorIndexRetriever.retrieve (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/indices/vectorStore/index.js:618:54)
[1]     at async DefaultContextGenerator.generate (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/engines/chat/DefaultContextGenerator.js:34:38)
[1]     at async ContextChatEngine.prepareRequestMessages (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/engines/chat/ContextChatEngine.js:451:25)
[1]     at async ContextChatEngine.chat (file:///C:/Users/HP/Desktop/rag/someli-chat/node_modules/llamaindex/dist/engines/chat/ContextChatEngine.js:418:33)


what might be the cause for this error and how should we fix this?

**Comment by marcusschiesser** [comment]
I guess that you're not using the same embedding model for retrieval as for ingestion. Make sure `initGemini` is called in both cases.
